name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: |
            pages_branch: gh-pages
            charts_dir: charts
